version: '3.8'
services:

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: student-info
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "aparna"
