spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student-info
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    server-port: 8090
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: postgresql